animal_diseases = {
        'dog': ['canine_parvovirus',
         'canine_distemper',
         'rabies',
         'kennel_cough',
         'canine_leptospirosis',
         'canine_ear_infection',
         'flea_allergy_dermatitis',
         'canine_arthritis',
         'canine_gastroenteritis',
         'canine_dermatitis'],
 'cat': ['rabies',
         'flea_allergy_dermatitis',
         'feline_panleukopenia',
         'feline_upper_respiratory_disease',
         'feline_herpesvirus',
         'feline_calicivirus',
         'feline_lower_urinary_tract_disease',
         'feline_dental_disease',
         'feline_flea_infestation',
         'feline_gastroenteritis',
         'feline_obesity',
         'feline_conjunctivitis'],
 'cattle': ['rabies',
            'foot_and_mouth_disease',
            'hemorrhagic_septicemia',
            'bovine_mastitis',
            'bovine_theileriosis',
            'bovine_babesiosis',
            'bovine_brucellosis',
            'bovine_tuberculosis',
            'bovine_ketosis',
            'bovine_milk_fever',
            'bovine_lumpy_skin_disease'],
 'buffalo': ['rabies',
             'foot_and_mouth_disease',
             'hemorrhagic_septicemia',
             'bovine_mastitis',
             'buffalo_mastitis',
             'buffalo_hemorrhagic_septicemia',
             'buffalo_foot_and_mouth_disease',
             'buffalo_brucellosis',
             'buffalo_babesiosis',
             'buffalo_theileriosis',
             'buffalo_milk_fever',
             'buffalo_ketosis',
             'buffalo_lumpy_skin_disease',
             'buffalo_internal_parasitism'],
 'goat': ['rabies',
          'foot_and_mouth_disease',
          'bovine_brucellosis',
          'ppr',
          'goat_enterotoxemia',
          'goat_coccidiosis',
          'goat_pneumonia',
          'goat_foot_rot',
          'goat_mange',
          'goat_worm_infestation',
          'goat_anemia',
          'goat_malnutrition'],
 'sheep': ['rabies',
           'foot_and_mouth_disease',
           'bovine_brucellosis',
           'ppr',
           'sheep_pox',
           'sheep_foot_rot',
           'sheep_coccidiosis',
           'sheep_enterotoxemia',
           'sheep_pneumonia',
           'sheep_internal_parasitism',
           'sheep_mange',
           'sheep_anemia',
           'sheep_malnutrition'],
 'horse': ['rabies',
           'equine_colic',
           'equine_gastric_ulcers',
           'equine_strangles',
           'equine_influenza',
           'equine_rhinitis',
           'equine_arthritis',
           'equine_laminitis',
           'equine_ringworm',
           'equine_mange',
           'equine_worm_infestation'],
 'pig': ['rabies',
         'foot_and_mouth_disease',
         'classical_swine_fever',
         'african_swine_fever',
         'swine_erysipelas',
         'swine_pneumonia',
         'swine_scabies',
         'swine_coccidiosis',
         'swine_gastroenteritis',
         'swine_anemia',
         'swine_mastitis_metritis_agalactia',
         'swine_internal_parasitism'],
 'chicken': ['newcastle_disease',
             'avian_influenza',
             'infectious_bronchitis',
             'infectious_bursal_disease',
             'coccidiosis_chicken',
             'fowl_pox',
             'mareks_disease',
             'chronic_respiratory_disease',
             'fowl_typhoid',
             'salmonellosis_chicken'],
 'rabbit': ['rabbit_coccidiosis',
            'rabbit_gastrointestinal_stasis',
            'rabbit_dental_disease',
            'rabbit_snuffles',
            'rabbit_mites',
            'rabbit_ringworm',
            'rabbit_encephalitozoonosis',
            'rabbit_pasteurellosis',
            'rabbit_pododermatitis',
            'rabbit_obesity']
}